apiVersion: v1
data:
  CLUSTER_NAME: Drone
  DATABASE_URL: mysql://restricted-host:3306/mysq56
  ENVIRONMENT: Dev
  REGION: East US
kind: ConfigMap
metadata:
  name: platform-config
  namespace: kalypso
